version: "3.8"
services:
  mongodb-test:
    image: mongo
    container_name: 'test-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb-init/test-mongodb-init.js:/docker-entrypoint-initdb.d/init-mongo-js:ro

