version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: 'local-mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=data
    ports:
      - '27017:27017'
    volumes:
      - ./docker-initdb/local-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data
    networks:
      - mongodb-app-network
networks:
  mongodb-app-network:
    driver: bridge
