version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: 'local-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=data
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb-init/local-mongodb-init.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./data:/data

