spring:
  config:
    import: "classpath:naver-cloud-key.yml,classpath:mongodb-local.yml"
  activate:
    on-profile: local
---
spring:
  config:
    import: "classpath:naver-cloud-key.yml,classpath:mongodb-test.yml"
  activate:
    on-profile: test
