spring:
  config:
    activate:
      on-profile: local
    import: "classpath:naver-cloud-key.yml,classpath:mongodb-local.yml"

---
spring:
  config:
    activate:
      on-profile: test
    import: "classpath:naver-cloud-key.yml,classpath:mongodb-test.yml"
