spring:
  data:
    mongodb:
      auto-index-creation: true
      username: dataUser
      password: password
      port: 27017
      database: data
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:~/data/kcbda
    driver-class-name: org.h2.Driver
    username: sa
