spring:
  data:
    mongodb:
      auto-index-creation: true
      username: testUser
      password: password
      port: 27018
      database: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
