version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: 'test-mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27018:27017'
    volumes:
      - ./test-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

